services:
  - type: web
    name: django-social-media
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn app.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings
      - key: SECRET_KEY
        value: hj%b(n&1c5l63c!w6spu86b46y4_7!m!&u5)*-^7^1c00ek=j6
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: django-social-media.onrender.com
     