# Generated by Django 5.1.4 on 2025-05-22 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webuserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.webuser')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('likes', models.IntegerField()),
                ('webuserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.webuser')),
            ],
        ),
    ]
