# Generated by Django 5.1.4 on 2025-05-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_followers_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webuser',
            old_name='phone',
            new_name='password',
        ),
    ]
