# Generated by Django 5.1.4 on 2025-05-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_rename_post_web_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='followers',
        ),
    ]
