# Generated by Django 5.1.4 on 2025-05-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('webpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.web_post')),
                ('webuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.webuser')),
            ],
        ),
    ]
