# Generated by Django 5.1.4 on 2025-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='ac_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=10),
        ),
    ]
