# Generated by Django 5.1.4 on 2025-05-23 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_delete_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webuser1Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='social.webuser')),
                ('webuser2Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='social.webuser')),
            ],
        ),
    ]
