# Generated by Django 5.1.4 on 2025-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='social.webuser'),
        ),
    ]
