# Generated by Django 5.1.4 on 2025-05-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
