# Generated by Django 5.1.4 on 2025-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_webuser_ac_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
