# Generated by Django 5.1.4 on 2025-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_webuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
