# Generated by Django 5.1.4 on 2025-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_webuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
